### ISSUE TITLE
Link to tutorials in torchdyn.readthedocs not working

### ISSUE THREAD

**Issue by AndreaPi** [DiffEqML/torchdyn#113]
**Describe the bug**

The link to the tutorials on the index page of torchdyn docs doesn't work

**Step to Reproduce**

1.  Go to https://torchdyn.readthedocs.io/en/latest/index.html
2. Click on the [here](https://github.com/diffeqml/torchdyn/tutorials) link
3. GitHub throws a 404 error: ![image](https://user-images.githubusercontent.com/8233615/127652078-f5559519-f75e-45d5-b071-77ab2a7fd7bc.png)

**Comment by Zymrael** [comment]
Thanks for spotting this. It will be fixed in a few minutes after the docs are finished rebuilding.

**Comment by AndreaPi** [comment]
Works now! Closing the issue
