### ISSUE TITLE
ModuleNotFoundError: No module named 'torchdyn'

### ISSUE THREAD

**Issue by SubhojitMandal-iiits** [DiffEqML/torchdyn#119]
Hello, I am new user for this package, unable to import it in Google Colab. It is throwing error as ' No module named 'torchdyn'', though I have installed the dependencies. It is installed in Colab as showing under python/3.8/site-packages but unable to import, can you help me regarding this?

**Comment by Zymrael** [comment]
Could you share the colab? Could be a misconfiguration problem, we haven't had issues like this outside colab environments.

**Comment by SubhojitMandal-iiits** [comment]
https://colab.research.google.com/drive/1ZQiVnF3Mrji99C3WVmmX6obHW-kawDQy?usp=sharing

Hello @Zymrael  I have attached the link of the colab file. Please check the issue. Thanks in advance.

**Comment by Zymrael** [comment]
The notebook is not accessible

**Comment by SubhojitMandal-iiits** [comment]
https://gist.github.com/SubhojitMandal-iiits/6482adf7e334fd23117fb7f48b6cee0e
From here you can access @Zymrael.

**Comment by Zymrael** [comment]
It seems you are getting the same `ModuleNotFoundError` for `pytorch-lightning` as well. I ran your notebook and got the same various packages installed. A mismatch between where you are installing and the kernel used for the notebook.
