### ISSUE TITLE
Model Hangs on First Epoch

### ISSUE THREAD

**Issue by nprasadmm** [DiffEqML/torchdyn#124]
I created a Graph Neural ODE using `torchdyn` where `f` is a 2-layer GCN made from `torch_geometric` layers and the model seems to run forever on the first epoch. When I print the output in the forward function for `f`, I constantly print the same values without end. I am unsure of any possible reasons for this. Could it be that the solver is failing to converge? Where should I look to debug this issue? I would appreciate any help.

**Comment by nprasadmm** [comment]
edit: I print the output at the end of the forward function for `f`.

**Comment by Zymrael** [comment]
Sounds like the solver is stuck rejecting the step due to high local error estimation. Are you using an adaptive solver i.e `dopri5` or `tsit5`? Does the issue persist with a fixed-step solver like `rk4`?

**Comment by nprasadmm** [comment]
I switched to `rk4` and it worked! Thank you!
