### ISSUE TITLE
CNF interface changes

### ISSUE THREAD

**Issue by atong01** [DiffEqML/torchdyn#128]
Thank you for the great codebase. I've been looking into your implementation and[ tutorial of continuous normalizing flows](https://github.com/DiffEqML/torchdyn/blob/49956acbbc59d1502719284c26015c98379e81ed/tutorials/module3-tasks/m3c_continuous_normalizing_flows.ipynb). It seems that this has been broken for a while due to some interface changes in `torchdyn`. I managed to get it working with some small changes to indexing and naming.

If you're interested I could fix up and submit a PR.

**Comment by joglekara** [comment]
Thanks for using the library and providing your feedback! 

Yes,`torchdyn` would love to have your input and bugfix so please feel free to submit a PR.

**Comment by Zymrael** [comment]
Thanks for #129, closing this for now!
