### ISSUE TITLE
No torchdyn in Python 3.7.12 in Kaggle and google colab

### ISSUE THREAD

**Issue by bigyaan** [DiffEqML/torchdyn#139]
**Describe the bug**
When I try to pip install torchdyn in google colab and kaggle I get the error:
ERROR: Could not find a version that satisfies the requirement torchdyn (from versions: none)
ERROR: No matching distribution found for torchdyn

**Step to Reproduce**

!pip install torchdyn on google colab
1. 
2. 
3. 
4. 

**Expected behavior**
install torchdyn

**Screenshots**

**Additional context**

**Comment by joglekara** [comment]
I am not sure what you mean by the Kaggle bit but I just tried

`!pip install torchdyn` in a new google colab notebook and it worked just fine. 

Can you please say more about how to reproduce?

TY!

**Comment by Zymrael** [comment]
This should have been fixed in `[1.0.2](https://github.com/DiffEqML/torchdyn/releases/tag/1.0.2)` as @joglekara mentioned. @bigyaan could you check again if pip installing works for you on Colab?

**Comment by bigyaan** [comment]
Yes I checked, it is finally working for some reason. Thank you
