### ISSUE TITLE
adaptive checkpoint adjoint solver

### ISSUE THREAD

**Issue by juntang-zhuang** [DiffEqML/torchdyn#14]
Hi, nice work. I wonder if it's possible to add adaptive checkpoint adjoint (ACA) solver as an option in this repo? 
We recently published a paper in ICML2020 and enable NODE to achieve (even outperform) ResNet on Cifar10, the code is published at https://github.com/juntang-zhuang/torch_ACA, and with paper https://arxiv.org/abs/2006.02493. I'm very glad if we can contribute to this nice project together and boost DiffEq in machine learning. Please contact me if you are interested, please also tell me if you have any ideas such as requirements on API.

**Comment by Zymrael** [comment]
Hi @juntang-zhuang! Nice coincidence, we were just about to email you and your team to discuss the inclusion of ACA in `torchdyn` :). At the moment, I see `ACA` as another option for the `sensitivity` argument in `NeuralDE`. We don't have super strict requirements on API; our general design philosophy is to reduce the number of arguments and options exposed to the user (to avoid confusion) and to implement features in a modular design. The biggest challenge for `ACA` would be implementing it with an eye towards future extensions (e.g. `SDE Adjoint`) that will inevitably need to be added to `torchdyn`.

I'll leave this issue open so we can discuss implementation details. Also, here is our [Slack](https://t.co/H1EpE18VfV?amp=1)

**Comment by juntang-zhuang** [comment]
Cool, thanks for your feedback, I'm happy to write some numerical solver suite. In my repository, the solver is completely re-written in order to only delete the redundant computation graph for the accuracy in grad, so it's not very consistent with ```torchdiffeq```, I can update it if you have any suggestions. Another problem is grad w.r.t time is not very convenient, and currently only supports tensor type output rather than tuple type (as in ```torchdiffeq```) in the derivative function. Will discuss it with you and see what's the best way, glad to join this project.

**Comment by Zymrael** [comment]
Since we've moved to discussing this new feature internally, I'm going to close this. For whoever is interested, you can join us via Slack.
