### ISSUE TITLE
Missing dependencies in setup.py

### ISSUE THREAD

**Issue by gileshd** [DiffEqML/torchdyn#16]
It seems that there are package dependencies which are not installed using `setup.py`. In particular it looks like matplotlib and scikit-learn are required.

Create a fresh environment and then, following the instructions in the README, install torchdyn with:

`git clone https://github.com/DiffEqML/torchdyn.git`

`cd torchdyn`

`python setup.py install`

However if you then try: `from torchdyn.models import *` it raises an error as matplotlib is not installed.

Similarly if you install matplotlib into the environment and then run `from torchdyn.datasets import *` you get an error as sklearn is not installed.

After installing both you these you can `from torchdyn import *` without error, so perhaps they are the only missing dependencies.

It would be great if these could be installed with `setup.py install`.

**Comment by massastrello** [comment]
Hi @gileshd, thank you for spotting the missing required dependencies. We'll proceed to fix the issue and add them to the `setup.py`.

**Comment by Zymrael** [comment]
We've added the missing dependencies. Worth noting how `torchdyn` dependency on `sklearn` is rather shallow (a single dataset in `static_datasets.py` requires `sklearn`), so we'll work on removing that altogether for the next mini-release. In the meantime, I'll keep this issue open.
