### ISSUE TITLE
Why is Neural Ode training  faster in CPU than in GPU?

### ISSUE THREAD

**Issue by bigyaan** [DiffEqML/torchdyn#161]
I am trying to train a Neural ODE in my local gpu to speed up my training. However, for my surprise it slowed the training rather than speeding it.
I have a nividia gtx 1060ti gpu with 4gb ram.
I have shared my code in given link below:
https://colab.research.google.com/drive/1DXFkPzOPeqBBmYON3TOtxi9tHwrUmgBs?usp=sharing

**Comment by joglekara** [comment]
Hey, we discussed this a bit over Slack so I'm closing this. Feel free to reopen if you would like to restart the discussion
