### ISSUE TITLE
dopri5 and tsit5 overestimate error

### ISSUE THREAD

**Issue by martenlienen** [DiffEqML/torchdyn#164]
The error estimates of the dopri5 and tsit5 solvers do not consider the step width `dt` in the error estimate which leads to overestimates of the error (assuming `dt < 1`)

https://github.com/DiffEqML/torchdyn/blob/master/torchdyn/numerics/solvers/ode.py#L155

https://github.com/DiffEqML/torchdyn/blob/master/torchdyn/numerics/solvers/ode.py#L177

**Comment by Zymrael** [comment]
Thanks! #165 addresses this. We observe a small speedup across our benchmarks.
