### ISSUE TITLE
Sklearn dependency push to pypi

### ISSUE THREAD

**Issue by atong01** [DiffEqML/torchdyn#180]
sklearn dependency is fixed on main branch but hasn't been pushed to pypi. Could a new version of torchdyn be pushed? Thanks!

I'm getting upstream test failures because of this: https://github.com/scikit-learn/sklearn-pypi-package

See here: https://github.com/atong01/conditional-flow-matching/actions/runs/4100542398/jobs/7071472166

**Comment by atong01** [comment]
Release 1.0.4 is not on pypi

**Comment by Zymrael** [comment]
Does this work for you? `https://pypi.org/project/torchdyn/1.0.4/`

**Comment by atong01** [comment]
yep, thanks Michael! 1.0.4 is on pypi, works on my end.
