### ISSUE TITLE
1.0.4 torchdyn not found

### ISSUE THREAD

**Issue by dsm-72** [DiffEqML/torchdyn#190]
install torchdyn 1.0.4
`import torchdyn` 
get error

**Comment by mr-mikmik** [comment]
same here

**Comment by OswaldZhang** [comment]
same

**Comment by denizhanpak** [comment]
Same but I think it's because pip install is only creating the dist-info file rather than installing the full package. Not sure why still working on it.

**Comment by mokandil** [comment]
I had the same issue when tried to install using pip install torchdyn. I tried to install the package directly from the GitHub repo. I tested it on Google Colab and everything works fine with me.

`pip install git+https://github.com/DiffEqML/torchdyn.git`

**Comment by jbmaxwell** [comment]
Same issue here. How do I get around it?

**Comment by maulberto3** [comment]
Hi, you might see my post useful: https://github.com/DiffEqML/torchdyn/issues/194#issuecomment-1648589685

**Comment by josephdviviano** [comment]
This commit fixed it - https://github.com/DiffEqML/torchdyn/commit/fcab1e2854d65f88c102c8f1259b8a905f8dbda0

they need to update the release.

**Comment by klee61** [comment]
I tried to install from the github source and get an error message that "Could not find a version that satisfies the requirement torch<2.0.0,>>=1.8.1 (from torchdyn). No matching distribution found for torch<2.0.0,>=1.8.1". Is it because it is compatible only torch version up to 1.8.1?

**Comment by atong01** [comment]
Fixed in release 1.0.5 https://github.com/DiffEqML/torchdyn/releases/tag/1.0.5.1

@klee61 this means that torchdyn currently requires torch version between 1.8.1 and 2.0.0
