### ISSUE TITLE
v0.3.0: `torchdyn` goes sequential

### ISSUE THREAD

**Issue by Zymrael** [DiffEqML/torchdyn#28]
Major:

- [ ] `HybridNeuralDE` API: modular ODE-RNN and friends
- [ ] `VariationalNeuralDE` API
- [x] `NeuralSDE` compatibility (`torchsde`)
- [ ] Cheap trace eval.: https://papers.nips.cc/paper/9187-neural-networks-with-cheap-differential-operators.pdf
- [ ] Adaptive checkpointing: https://arxiv.org/abs/2006.02493

Minor:

- [ ] A variety of `TimeSeriesDataset`
- [ ] Optimal control example
- [x] Improved image classification architecture and tutorial 
- [x] `DC` and `Stable` normalizing flow tutorials

Miscellaneous:

- [ ] Performance tests

**Comment by Zymrael** [comment]
Hey @kivo360, thank you for offering to help! [Join us in Slack](https://join.slack.com/t/diffeqml/shared_invite/zt-gq3jjj5x-LuHSB4m4gc9MsnvoF1UB6A), we'll find together a first contribution that's interesting and can help you get familiar with the codebase.

**Comment by ExtinctionEvent** [comment]
Hello, Id like to contribute to this, if that is possible.

**Comment by Zymrael** [comment]
We're a bit busy with NeurIPS at the moment, but feel free to join us on Slack - unless you've joined already (and posted on `#torchdyn-dev`?)

**Comment by lucaslie** [comment]
I was wondering if there is any progress on including adaptive checkpointing? 

Sounds like a really useful addition to the repo. :)

**Comment by Zymrael** [comment]
We had to pause active development due to other obligations, but there should be more coming in the third quarter of 2021, including some of the newer advances in the field.

**Comment by Zymrael** [comment]
Closing as we're jumping ahead to `v1.0` with a whole host of [new features](https://github.com/DiffEqML/torchdyn/issues/82) (currently in dev.)
