### ISSUE TITLE
The Slack invite does not work!

### ISSUE THREAD

**Issue by Raahul-Singh** [DiffEqML/torchdyn#29]
Hi guys!
I want to contribute to this project, I tried joining the slack channel, but was not able to.
Could you please have a look at it? It says the invite has expired.

**Comment by Zymrael** [comment]
Hi @Raahul-Singh, thank you for your interest. You should be able to join Slack via [this link](https://join.slack.com/t/diffeqml/shared_invite/zt-g7orrpg1-f8V7gCJOBFJ_wuUFVEt1eg). 

We'll keep this issue open for now as we figure out a way to automate invitations. For other contributors wishing to join the conversation on Slack, feel free to drop a comment here and we'll reach out.

**Comment by Raahul-Singh** [comment]
Thanks @Zymrael  :)

**Comment by Zymrael** [comment]
The link is now working and several new members have joined, closing.
