### ISSUE TITLE
Drop Windows support?

### ISSUE THREAD

**Issue by Raahul-Singh** [DiffEqML/torchdyn#32]
This issue it to keep a track of the conversation that started on the slack channel

**Comment by Zymrael** [comment]
I'll take a look at the failing test, if it's easy to fix we'll keep supporting Windows for now. We note that most of `torchdyn` works on Windows out-of-the-box, and it is really only rare dependency issues that arise during installation that can cause problems.

**Comment by Zymrael** [comment]
We will keep supporting Windows for now.
