### ISSUE TITLE
How to print the number of integration steps?

### ISSUE THREAD

**Issue by cyx96** [DiffEqML/torchdyn#48]
Hi, I was playing with your FFJORD tutorial (really nice tutorial btw). And I'm curious about if there is a way to print the number of integration steps taken during the training or sampling process.

**Comment by massastrello** [comment]
Hi, a simple way of doing that is to use the `progress_bar `of `PyTorch-Lightning`. If that is sufficient to you, you may redefine the `Learner` as 

```
class Learner(pl.LightningModule):
    def __init__(self, model:nn.Module):
        super().__init__()
        self.model = model
        self.iters = 0

    def forward(self, x):
        return self.model(x)

    def training_step(self, batch, batch_idx):
        self.iters += 1
        x = batch[0]
        xtrJ = self.model(x)
        logprob = prior.log_prob(xtrJ[:,1:]).to(x) - xtrJ[:,0] # logp(z_S) = logp(z_0) - \int_0^S trJ
        progress_dict = {"nfe": nde.nfe}
        loss = -torch.mean(logprob)
        nde.nfe = 0
        return {'loss': loss, 'progress_bar': progress_dict}

    def configure_optimizers(self):
        return torch.optim.AdamW(self.model.parameters(), lr=2e-3, weight_decay=1e-5)

    def train_dataloader(self):
        return trainloader
```

**Comment by massastrello** [comment]
Actually, `nfe` is not exactly equivalent to the number of integration steps of the ODE solver but rather the number of times the `defunc` is evaluated (i.e. proportional to it). For example, let `s_span=torch.linspace(0, 1, 10)`; if you use `"euler"` you will get `nde.nfe=9` while if you use `"rk4"` you will get `nfe.nde=36`. Nonetheless, in both solvers performed 9 steps
