### ISSUE TITLE
ModuleNotFoundError: No module named 'torchdyn.models'

### ISSUE THREAD

**Issue by drozzy** [DiffEqML/torchdyn#55]
If i follow the tutorial, using torchdyn 0.2.2.1:
```
from torchdyn.models import *
```
I get this error:
```
ModuleNotFoundError: No module named 'torchdyn.models'
```

**Comment by ucalyptus** [comment]
@drozzy do you have a gist colab nb to reproduce the issue?

**Comment by drozzy** [comment]
Just `from torchdyn.models import *` this one line...

**Comment by drozzy** [comment]
Oh nevermind, I just needed to restart ipython
