### ISSUE TITLE
Missing plots on 05 tutorial

### ISSUE THREAD

**Issue by drozzy** [DiffEqML/torchdyn#56]
This page doesn't show the plots themselves (see bottom of the page):
https://torchdyn.readthedocs.io/en/latest/tutorials/05_generalized_adjoint.html
Would be nice if they were included like in other tutorials.

**Comment by Zymrael** [comment]
Thank you for spotting that inconsistency - this will likely be fixed in the next release, when we'll update the tutorials according to new `PyTorch-Lightning` best practices (and small internal API changes)

**Comment by Zymrael** [comment]
All tutorials have been updated.
