### ISSUE TITLE
HybridNeualDE can't output CUDA tensors

### ISSUE THREAD

**Issue by qpwodlsqp** [DiffEqML/torchdyn#73]
**Describe the bug**
```
Y = torch.zeros(x.shape[0], *h.shape)
if self.reverse: x_t = x_t.flip(0)
for t, x_t in enumerate(x):
    h, c = self.jump_func(x_t, h, c)
    h = self.flow(h)
    Y[t] = h
Y = self.out(Y)
```
In the line 23~29 of [hybrid.py](https://github.com/DiffEqML/torchdyn/blob/master/torchdyn/seq/hybrid.py), the `Y` remains as CPU tensor after it is initialized even if `HybridNeuralDE` parameters and input tensor are placed on GPU.
This causes an error in the line 29 when a model is placed on GPU.
I am currently using torch==1.7.1 and torchdyn==0.2.2.1

**Comment by Zymrael** [comment]
I believe that should be fixed by modifying line 1 to `Y = torch.zeros(x.shape[0], *h.shape).to(x)` to force agreement between devices and types. Feel free to PR if that ends up working :)

**Comment by qpwodlsqp** [comment]
confirmed that modification works and made a [pull request](https://github.com/DiffEqML/torchdyn/pull/74)
