### ISSUE TITLE
Trajectory

### ISSUE THREAD

**Issue by pharringtonp19** [DiffEqML/torchdyn#78]
The model that I am training is very similar to ANODE as defined in torchdyn/tutorials/04_augmentation_strategies.ipynb

Given a time step in [0,1], I would like to get the "flow" of the model at that time step - more specifically the flow for a batch of data (I hope my language is correct!). Chen (2018) writes that "Most ODE solvers have the option to output the state z(t) at multiple times." Is there a way to do this torchdyn when using neuralDE and Augmenter? I was hoping to pass these flows into another function -- thanks

**Comment by Zymrael** [comment]
Hi @pharringtonp19. That can be achieved through the `trajectory` method of `NeuralODE`, see [here](https://github.com/DiffEqML/torchdyn/blob/31c1e8f134b300e4762e490e0af77c9f73ad8bd9/torchdyn/core/neuralde.py#L156). Note that if you would still want to use the adjoint method, you'd have to modify the `torchdiffeq` call with `odeint_adjoint`

**Comment by pharringtonp19** [comment]
@Zymrael Thanks for the explanation

**Comment by Zymrael** [comment]
Cool! Closing for now.
