### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by pharringtonp19** [DiffEqML/torchdyn#80]
This might be a bad question --

Is there a way to initialize the model/vector field so that if no training was performed, you would simply get the input as the output?

**Comment by Zymrael** [comment]
Hi @pharringtonp19. You can try [initializing parameters](https://pytorch.org/docs/stable/_modules/torch/nn/init.html#zeros_) of the last layer in `DEFunc` close to 0 (initializing all to 0 can be dangerous). This will make you vector field small everywhere i.e $\dot x$ close to zero, and the integral over your specified time domains also close to 0. In other words, your Neural ODE output will be also close to your initial condition.
