### ISSUE TITLE
A new model?

### ISSUE THREAD

**Issue by jbgao** [DiffEqML/torchdyn#81]
**Describe the solution you'd like**

If my vector field function is in the form of f(z(t), x(t)), where z the solution of ODE where x(t) is a known control input, can we have a model in TorchDyn for this type ODE.     Or this has been considered?  Any hints or suggestions?

J.

**Comment by Zymrael** [comment]
This can be easily done by concatenating `z, x` and then using them inside the ODE function. We have examples of this in our optimal control tutorials.
