### ISSUE TITLE
Easy to Train Neural ODE

### ISSUE THREAD

**Issue by pharringtonp19** [DiffEqML/torchdyn#82]
Really enjoying the library so far --

I was wondering if there was any thoughts about implementing the regularization method introduced in [Kelly 2020](https://arxiv.org/pdf/2007.04504.pdf). I would be more than happy to assist in the implementation. 

Thanks

**Comment by Zymrael** [comment]
Hi @pharringtonp19. We'd be glad to have that in the library. We're currently undergoing a major redesign of API and functionality in preparation for a `v1.0` release. I'll ping you here once the API is stable enough that work on higher-level features such as regularization techniques is possible with minimal hassle on your end.

**Comment by Zymrael** [comment]
`0.3.1` will go up later this week. There is still a lot happening around the numerical methods API but `odeint`, `ODEProblem` and `NeuralODE` should be stable enough for you to start. To implement regularizers, I would start with trying to reproduce some of their results on toyish examples in a notebook; after that we can think about how to best incorporate the method in the library (perhaps hiding it under some well designed abstraction grouping several regularizers, we'll see)

**Comment by pharringtonp19** [comment]
I have a partial implementation of this now in JAX. Once I have it complete, I will see if I can write it up in torchdyn

![regularized_neural_ode](https://user-images.githubusercontent.com/55798098/126322464-9adecc65-ed65-422b-9f9c-12fc9a85fed0.png)

**Comment by Zymrael** [comment]
Awesome! Let me know if you encounter difficulties.

**Comment by Zymrael** [comment]
Any news on this front? Would be cool to add this for our next small release.

**Comment by pharringtonp19** [comment]
@Zymrael Through discussions with one of the authors on the paper, I realized that my implementation was not efficient. I can close this issue now and re-open it once I have a "complete" working version of this in jax. - Thanks
