### ISSUE TITLE
NeuralDE in the documentation?

### ISSUE THREAD

**Issue by javirk** [DiffEqML/torchdyn#86]
I am seeing in the docs ([classification ](https://torchdyn.readthedocs.io/en/latest/tutorials/02_classification.html) or [Lagrangian neural nets](https://torchdyn.readthedocs.io/en/latest/tutorials/09_lagrangian_nets.html) tutorials) that the ODE is instantiated as `NeuralDE`. When I try it in my environment, with torchdyn 0.2.0, I get `NameError: name 'NeuralDE' is not defined`. However, the [tutorials in github](https://github.com/DiffEqML/torchdyn/blob/master/tutorials/09b_lagrangian_nets.ipynb) say it's `NeuralODE`, and that works for me.

Are the docs wrong or `NeuralDE` and `NeuralODE` are two different things and I'm doing something wrong?

Thanks!

**Comment by javirk** [comment]
Ok, I created a new environment, reinstalled torchdyn & Co. and now there are no problems with `NeuralDE`. 
```
pytorch 1.9+cuda10.2
torchdyn 0.2.2.1
torchdyn 0.2.2.1
torchsde 0.2.5i
```

But then the [tutorials](https://github.com/DiffEqML/torchdyn/tree/master/tutorials) are not updated. I would do a PR but I don't know if they're kept like that for some reason.

**Comment by Zymrael** [comment]
Hi @javirk. The docs are outdated in several places and will be massively improved for the next release planned for early July. `NeuralDE` is the legacy version kept for backward compatibility, which has now been replaced by  `NeuralODE`.

Out of curiosity, did you install `torchdyn` via `pip`? `0.2.2.1` is outdated and `0.3.2` should be on PyPI.

**Comment by javirk** [comment]
Yes, I installed it via `pip`. I just tried in a blank new environment and it retrieves `0.2.2.1` for some reason. I have `pip 21.1.3` (last version).

![image](https://user-images.githubusercontent.com/3169791/123537695-132cbb00-d731-11eb-8d34-a922d929a143.png)

**Comment by Zymrael** [comment]
`pip install torchdyn` with pip `21.1.3` retrieves `torchdyn==0.4.1` for me at the moment, check if this works on your end as well.

**Comment by javirk** [comment]
Yes, it works now. Thank you very much.

I think this can be closed now.
