### ISSUE TITLE
Where is plot_2D_depth_trajectory( ) ?

### ISSUE THREAD

**Issue by dbuskirk** [DiffEqML/torchdyn#89]
I am sure I must be overlooking something obvious, but I am trying to work through the torchdyn tutorials and I am not able to find plot_2D_depth_trajectory( ) .

**Comment by Zymrael** [comment]
Those utilities are [here ](https://github.com/DiffEqML/torchdyn/blob/master/torchdyn/utils.py), though we'll be moving them in the same `tutorial` folder next patch.

**Comment by dbuskirk** [comment]
Thank you for your prompt reply. Much appreciated.

________________________________
