### ISSUE TITLE
Known issues and incompatibilities

### ISSUE THREAD

**Issue by Zymrael** [DiffEqML/torchdyn#9]
- [x] `DataControl` with `CNF` requires testing. Compatible but unreliable
- [x] `Galerkin` layers with `CNF` requires testing. Compatible but unreliable
- [x] Loading `NeuralDE`  via `torch.load` or `.load_state_dict` sometimes causes issue due to `Adjoint` class. Can be fixed by dropping excess `state_dict` keys.
- [x] Training issue in notebook `05`

- [x] Issue with `02_classification` on Windows due to `pytorch-lightning` issues. See [#2358](https://github.com/PyTorchLightning/pytorch-lightning/pull/2358). EDIT: Should be fixed.

**Comment by Zymrael** [comment]
* AttributeError: module 'torchdyn.models.defunc

**Comment by Mikkolehtimaki** [comment]
> Loading NeuralDE via torch.load or .load_state_dict sometimes causes issue due to Adjoint class. Can be fixed by dropping excess state_dict keys.

What keys  are 'excess'?

**Comment by Zymrael** [comment]
The whole `API` has been reworked, and this issue should be fixed.
